Vagrant.configure("2") do |config|
  config.vm.box = "rockylinux/9"

  # config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  # config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "public_network"
  
  # config.vm.synced_folder "../data", "/vagrant_data"
  # config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end

  # Primer disco
  config.vm.disk :disk, name: "disco1", size: "10GB"

  # Segundo disco
  config.vm.disk :disk, name: "disco2", size: "20GB"

  config.vm.provision "shell", inline: <<-SHELL
    dnf install lvm2 -y
  SHELL
end
